config/routes.rb
Rails.application.routes.draw do
  get '/home', to: 'pages#home' 
  root :to => "pages#home"
  resources :recipes do
    member do
      post 'like'
    end
  end
  
  resources :chefs, except: [:new, :destroy]
  
  resources :reviews, only: [:create,:update]
  get 'new/:recipe_id', to: 'reviews#new', as: 'new_review'
  get 'index/:recipe_id', to: 'reviews#index', as: 'all_reviews'
  get 'edit/:id', to: 'reviews#edit', as: 'edit_review'
  
  get '/register', to: 'chefs#new'
  
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'
  
  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :chef
  has_many :likes, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :recipe_styles, dependent: :destroy
  has_many :styles ,through: :recipe_styles
  has_many :recipe_ingredients, dependent: :destroy
  has_many :ingredients ,through: :recipe_ingredients
  validates :chef_id, presence: true
  validates :name, presence: true, length: { minimum: 5, maximum: 100 }
  validates :summary, presence: true, length: { minimum: 10, maximum: 300 }
  validates :description, presence: true, length: {minimum: 20,maximum:1500 }
  mount_uploader :picture, PictureUploader
  validate :picture_size
  
  default_scope -> { order(updated_at: :desc) }
  
  def thumbs_up_total
    self.likes.where(like: true).size
  end
  
  def thumbs_down_total
    self.likes.where(like: false).size
  end
  
  private
    def picture_size 
      if picture.size > 5.megabytes
        errors.add(:picture,"should be less than 5MB")
      end
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
   
   before_action :set_recipe, only: [:edit,:update,:like, :show]
   before_action :require_user, except: [:index, :show, :like]
   before_action :require_user_likes, only: [:like]
   before_action :require_same_user, only: [:edit, :update]
   before_action :admin_user, only: [:destroy]
   
   def index
       @recipes = Recipe.paginate(page: params[:page],per_page: 4)
   end
   
   def show
      
   end
   
   def destroy
      Recipe.find(params[:id]).destroy
      flash[:success] = "Recipe deleted"
      redirect_to recipes_path
   end
   
   def new
      @recipe = Recipe.new
   end
   
   def create
      @recipe = Recipe.new(recipe_params)
      @recipe.chef =current_user
      
      if @recipe.save
         flash[:success] = "Your recipe was created successfully!"
         redirect_to recipes_path
      else
         render :new
      end
   end
   
   def edit

   end
   
   def update
        
      if @recipe.update(recipe_params)
         flash[:success] = "Your recipe was updated!!"
         redirect_to recipe_path(@recipe)
      else
         render :edit
      end
   end
   
   def like
      like = Like.create(like: params[:like],chef: current_user, recipe: @recipe)
      if like.valid?
        flash[:success]="Your selection was successful"
        redirect_to :back
     else
        flash[:danger]="You can only like/dislike a recipe only once!"
        redirect_to :back
     end
   end
   
   private
     def recipe_params
        params.require(:recipe).permit(:name,:summary,:description,:picture,style_ids: [],ingredient_ids: [])
     end
     
     def set_recipe
        @recipe = Recipe.find(params[:id])
     end
     
     def require_same_user
        if current_user != @recipe.chef and !current_user.admin?
           flash[:danger] = "You can only edit your recipes"
           redirect_to recipes_path
        end
     end
     
     def require_user_likes
        if !logged_in?
           flash[:danger] = "You must be logged in to perform this action!"
           redirect_to :back
        end
     end
     
     def admin_user
        redirect_to recipes_path unless current_user.admin?
     end
end

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>

<div class="row">
    <div class = "col-md-8 col-md-offset-2 well">
        <%= form_for(@recipe, html: { multipart: true }) do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>
        <%= f.label :summary %>
        <%= f.text_field :summary %>
        <%= f.label :description %>
        <%= f.text_area :description ,rows: 10%>
        
        <strong>Styles:</strong>
            <%= f.collection_check_boxes :style_ids, Style.all, :id, :name do |cb| %>
              <% cb.label(class: "checkbox-inline input_checkbox"){cb.check_box(class: "checkbox") +  cb.text} %>
            <% end %>
        <br><br>
      
        <strong>Ingredients:</strong>
             <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |cbi| %>
              <% cbi.label(class: "checkbox-inline input_checkbox"){cbi.check_box(class: "checkbox") +  cbi.text} %>
             <% end %>
       <br><br>
         
        <span class="picture">
            <%= f.file_field :picture,accept: 'image/jpeg,image/png,image/gif' %>
        </span>
        <%= f.submit(@recipe.new_record? ? 'Create Recipe' : 'Edit Recipe',class: "btn btn-success") %>
        <% end %>
    </div>
</div>

<script type="text/javascript">
    $('#recipe_picture').bind('change',function() {
        size_in_megabytes=this.files[0].size/1024/1024;
        if (size_in_megabytes > 5) {
            alert('Maximum file size is 5MB. Please choose a smaller file');
        }
    });
</script> 

app/views/recipes/edit.html.erb
<%= render 'shared/page_title',title: "Edit this Recipe" %>

<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title',title: "All Recipes" %>

<ul class="nav nav-tabs">
    <li class="active">
        <%= link_to "Recipes",recipes_path %>
    </li>
    <li>
        <%= link_to "Chefs",chefs_path %>
    </li>
    
</ul>

<%= will_paginate %>

<% @recipes.each do |recipe| %>

<div class="row">
    
    <div class="col-md-2">
        <section class="chef_info center">
            <%= link_to gravatar_for(recipe.chef,size: 100), chef_path(recipe.chef)%> <!-- gravatar_for is user defined method present in helpers -->
            <h5>Chef name : <%= recipe.chef.chefname %></h5>
        </section>
    </div>
    
    <div class="col-lg-6 well">
        <h4><%= link_to recipe.name,recipe_path(recipe) %></h4>
        <p><%= recipe.summary %></p>
        <% if recipe.styles.any? %>
          <p>Style : <%= render recipe.styles %></p>
        <% end %>
        <% if recipe.ingredients.any? %>
          <p>Ingredients : <%= render recipe.ingredients %></p>
        <% end %>
        <p>
            <small> <span class="text-muted">created: <%= time_ago_in_words(recipe.created_at) %>, </span> </small>
            <small> <span class="text-muted">updated: <%= time_ago_in_words(recipe.updated_at) %> </span> </small>
        </p>
        <div class="pull-right">
            <%=link_to like_recipe_path(recipe,like: true), method: :post do %>
                <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= recipe.thumbs_up_total %>
            <%end%>&nbsp&nbsp&nbsp&nbsp
            <%=link_to like_recipe_path(recipe,like: false), method: :post do %>
                 <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= recipe.thumbs_down_total %>
            <%end%>
        </div>
    </div>
    
    <div class="col-md-4">
        <%= image_tag(recipe.picture.url,size: "250x150", class: "gravatar") if recipe.picture? %>
    </div>

</div>

<hr/>
<% end %>

<%= will_paginate %>

app/views/recipes/new.html.erb
<%= render 'shared/page_title',title: "Create a Recipe" %>
<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title',title: @recipe.name %>
<div class="row">
    <div class= "col-md-4 pull-right center">
        <%= link_to (gravatar_for @recipe.chef,size: 200), chef_path(@recipe.chef) %>
        <p>
            <h4>Brought to you by : <%= @recipe.chef.chefname %> </h4>
        </p>
    </div>
    <div class ="col-md-8">
        <% if logged_in? and (current_user == @recipe.chef || current_user.admin?) %>
          <%= link_to "Edit this recipe",edit_recipe_path(@recipe), class: "btn btn-success pull-right" %>
        <% end %>
        <% if logged_in? and current_user.admin?  %>
          <%= link_to "[Delete Recipe]", @recipe, method: :delete, data: { confirm: "Are you sure?" } %>
        <% end %>
        <br><br>
        <h3><%= @recipe.summary %></h3>
        <div class="show_recipe">
            <%= image_tag(@recipe.picture.url,class: "gravatar") if @recipe.picture? %>
        </div>
        <div class="well">
            <% if @recipe.styles.any? %>
              <p>Style : <%= render @recipe.styles %></p>
            <% end %>
            <% if @recipe.ingredients.any? %>
              <p>Ingredients : <%= render @recipe.ingredients %></p>
            <% end %>
            <p>
                <strong>Steps:</strong>
            </p>
            <%= simple_format(@recipe.description) %>
            <div class="pull-right">
                <%=link_to like_recipe_path(@recipe,like: true), method: :post do %>
                  <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= @recipe.thumbs_up_total %>
                <%end%>&nbsp&nbsp&nbsp&nbsp
                <%=link_to like_recipe_path(@recipe,like: false), method: :post do %>
                  <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= @recipe.thumbs_down_total %>
                <%end%>
            </div>
        </div>
        <strong><hr></strong>
        <% if logged_in? %> 
          <% if current_user.reviews.find_by(recipe: @recipe)==nil %>
          <%= link_to "Write Review",new_review_path(@recipe), class: "btn btn-success pull-right" %>
          <% else %>
          <br>
          <h4>My Review:</h4>
          <div class="row">
              <div class = "col-md-12 well">
                  <%= link_to "Edit",edit_review_path(current_user.reviews.find_by(recipe: @recipe)), class: "btn btn-success pull-right" %>
                  <br><br>
                  <strong><i><%= current_user.reviews.find_by(recipe: @recipe).review %></i></strong>
                  
              </div>
          </div>
        <% end %>
        <% end %>
    </div>
    
</div>
<h5> <%= link_to "View All Reviews", all_reviews_path(@recipe), class: "btn btn-small btn-warning" %></h5>
<br>
<h5> <%= link_to "Back to All Recipes", recipes_path, class: "btn btn-small btn-warning" %></h5>