config/routes.rb
Rails.application.routes.draw do
  get '/home', to: 'pages#home' 
  root :to => "pages#home"
  resources :recipes do
    member do
      post 'like'
    end
  end
  
  resources :chefs, except: [:new, :destroy]
  
  resources :reviews, only: [:create,:update]
  get 'new/:recipe_id', to: 'reviews#new', as: 'new_review'
  get 'index/:recipe_id', to: 'reviews#index', as: 'all_reviews'
  get 'edit/:id', to: 'reviews#edit', as: 'edit_review'
  
  get '/register', to: 'chefs#new'
  
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'
  
  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]
end

app/views/pages/home.html.erb
<div class="container">
  <div class="center jumbotron">
    <h1>Welcome to My Receipe App</h1> 
    <h2><i>A recipe has no soul, you as the cook must bring soul to the recipe.</i></h2> 
    <div class="center">
        <%= link_to "Sign Up",register_path,class: "btn btn-lg btn-success"%>
    </div>
  </div>
</div>
<div class="row">
    
    <div class="col-lg-4">
        <h3 class="midrow">
            View recipes as Guest User
        </h3>
        <h2 class="left">
            Browse and view recipes as a guest and sign up later
        </h2>
        <p>
            <%= link_to "Browse Recipe Listings",recipes_path,class: "btn btn-small btn-warning"%>
        </p>
    </div>
    
    <div class="col-lg-4">
        <h3 class="midrow">
            Sign in to your account
        </h3>
        <h2 class="left">
            Add / Update your recipes / create reviews /like-dislike recipes and much more!!
        </h2>
        <p>
            <%= link_to "Login to your account",login_path,class: "btn btn-small btn-warning"%>
        </p>
    </div>
    
    <div class="col-lg-4">
        <h3 class="midrow">
            View recipes as Guest User
        </h3>
        <h2 class="left">
            Browse and view recipes as a guest and sign up later
        </h2>
        <p>
            <%= link_to "Browse Recipe Listings",recipes_path,class: "btn btn-small btn-warning"%>
        </p>
    </div>
</div>